repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/ansible/ansible-lint
    rev: v4.2.0
    hooks:
      - id: ansible-lint
        files: \.ya?ml$

  - repo: https://github.com/me-vlad/ansible-pre-commit
    rev: v0.1.3
    hooks:
      - id: encryption-check
