---

- name: Download Wowza installer
  get_url:
    url: "{{ wowza_download_path }}{{ wowza_installer }}"
    dest: "{{ wowza_install_workdir }}/{{ wowza_installer }}"
    owner: root
    group: root
    mode: '0755'
    force: no
    checksum: "{{ wowza_installer_checksum }}"
  when:
    - wowza_download_path | length > 0
    - wowza_installer | length > 0
    - wowza_installer_checksum | length > 0

- name: Ensure expect is installed
  package: name=expect state=installed

- name: Create expect script on the server
  template:
    src: "{{ wowza_install_script }}.j2"
    dest: "{{ wowza_install_workdir }}/{{ wowza_install_script }}"
    owner: root
    group: root
    mode: "0700"

- name: Run expect script for WSE install
  command:
    cmd: "{{ wowza_install_workdir }}/{{ wowza_install_script }}"
    creates: "{{ wowza_license_file }}"
  register: wowza_expect_output
  when:
    - wowza_license_key | length > 0
    - wowza_user | length > 0
    - wowza_password | length > 0

- name: Print a good news (if any)
  shell: "echo '{{ '='*15 }} {{ red }}Wowza Streaming Engine successfully installed!{{ CSI }}0m {{ '='*15 }}' > /dev/tty"
  changed_when: no
  become: no
  delegate_to: localhost
  vars:
    CSI: "\x1B["
    red: '{{ CSI }}31m'
  when:
    - wowza_expect_output.stdout | length > 0
    - wowza_expect_output.stdout.find("Setup has finished installing Wowza Streaming Engine on your computer.") != -1

- name: Remove expect script and installer from server
  file:
    name: "{{ item }}"
    state: absent
  loop:
    - "{{ wowza_install_workdir }}/{{ wowza_install_script }}"
    - "{{ wowza_install_workdir }}/{{ wowza_installer }}"
    - "{{ wowza_install_workdir }}/.bitrock/"
