---

- name: WOWZA | Download Wowza installer
  get_url:
    url: "{{ wowza_download_path }}{{ wowza_installer }}"
    dest: "{{ wowza_install_workdir }}/{{ wowza_installer }}"
    owner: root
    group: root
    mode: '0700'
    force: false
    checksum: "{{ wowza_installer_checksum }}"
  when:
    - wowza_download_path | length > 0
    - wowza_installer | length > 0
    - wowza_installer_checksum | length > 0

- name: WOWZA | Ensure expect is installed
  package:
    name: expect
    state: present

- name: WOWZA | Create expect script on the server
  template:
    src: "{{ wowza_install_script }}.j2"
    dest: "{{ wowza_install_workdir }}/{{ wowza_install_script }}"
    owner: root
    group: root
    mode: "0700"
  no_log: true

- name: WOWZA | Run expect script for WSE install
  command:
    cmd: "{{ wowza_install_workdir }}/{{ wowza_install_script }}"
    creates: "{{ wowza_license_file }}"
  no_log: true
  register: wowza_expect_output
  when:
    - wowza_license_key | length > 0
    - wowza_admin_user | length > 0
    - wowza_admin_password | length > 0

- name: WOWZA | Print install finish info
  debug:
    msg: "Wowza Streaming Engine successfully installed!"
    verbosity: 0
  when:
    - wowza_expect_output.stdout | length > 0
    - wowza_expect_output.stdout.find("Setup has finished installing Wowza Streaming Engine on your computer.") != -1

- name: WOWZA | Remove expect script and installer from server
  file:
    name: "{{ item }}"
    state: absent
  loop:
    - "{{ wowza_install_workdir }}/{{ wowza_install_script }}"
    - "{{ wowza_install_workdir }}/{{ wowza_installer }}"
    - "{{ wowza_install_workdir }}/.bitrock/"
