---

- name: wowza reload systemd
  systemd: daemon_reload=yes

- name: restart wse
  service: name=WowzaStreamingEngine state=restarted

- name: restart wse manager
  service: name=WowzaStreamingEngineManager state=restarted
