---

- name: WOWZA | reload systemd
  systemd: daemon_reload=yes

- name: WOWZA | restart WSE
  service: name=WowzaStreamingEngine state=restarted

- name: WOWZA | restart WSE Manager
  service: name=WowzaStreamingEngineManager state=restarted
